# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: domain.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'domain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64omain.proto\x12\noddsengine\"`\n\x06\x45ntity\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08sport_id\x18\x03 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x04 \x01(\t\x12\x15\n\rmetadata_json\x18\x05 \x01(\t\"~\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08sport_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\r\n\x05venue\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x06 \x01(\t\x12\x15\n\rmetadata_json\x18\x07 \x01(\t\"a\n\x0bParticipant\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x18\n\x10result_data_json\x18\x03 \x01(\t\x12\x13\n\x0b\x66inish_rank\x18\x04 \x01(\x05\"\xa0\x01\n\x0eRatingSnapshot\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x10\n\x08sport_id\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x0e\n\x06rating\x18\x04 \x01(\x01\x12\x18\n\x10rating_deviation\x18\x05 \x01(\x01\x12\x12\n\nvolatility\x18\x06 \x01(\x01\x12\x17\n\x0f\x61s_of_timestamp\x18\x07 \x01(\x03\"\xaf\x01\n\x10PredictionRecord\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12$\n\x1cpredicted_outcome_probs_json\x18\x03 \x01(\t\x12\x1d\n\x15predicted_result_json\x18\x04 \x01(\t\x12\x14\n\x0cgenerated_at\x18\x05 \x01(\x03\x12\x1a\n\x12\x61\x63tual_result_json\x18\x06 \x01(\tB\x18\n\x14\x63om.oddsengine.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'domain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.oddsengine.protoP\001'
  _globals['_ENTITY']._serialized_start=28
  _globals['_ENTITY']._serialized_end=124
  _globals['_EVENT']._serialized_start=126
  _globals['_EVENT']._serialized_end=252
  _globals['_PARTICIPANT']._serialized_start=254
  _globals['_PARTICIPANT']._serialized_end=351
  _globals['_RATINGSNAPSHOT']._serialized_start=354
  _globals['_RATINGSNAPSHOT']._serialized_end=514
  _globals['_PREDICTIONRECORD']._serialized_start=517
  _globals['_PREDICTIONRECORD']._serialized_end=692
# @@protoc_insertion_point(module_scope)
