# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import domain_pb2 as domain__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\noddsengine\x1a\x0c\x64omain.proto\"^\n\x0b\x45ventResult\x12 \n\x05\x65vent\x18\x01 \x01(\x0b\x32\x11.oddsengine.Event\x12-\n\x0cparticipants\x18\x02 \x03(\x0b\x32\x17.oddsengine.Participant\"?\n\x0eRatingResponse\x12-\n\tsnapshots\x18\x01 \x03(\x0b\x32\x1a.oddsengine.RatingSnapshot\"o\n\x0ePredictRequest\x12\x10\n\x08sport_id\x18\x01 \x01(\t\x12\x1e\n\x16participant_entity_ids\x18\x02 \x03(\t\x12\x17\n\x0f\x61s_of_timestamp\x18\x03 \x01(\x03\x12\x12\n\nmodel_name\x18\x04 \x01(\t\"9\n\rSeasonRequest\x12\x11\n\tleague_id\x18\x01 \x01(\t\x12\x15\n\rn_simulations\x18\x02 \x01(\x05\"E\n\x16SeasonSimulationResult\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x18\n\x10rank_frequencies\x18\x02 \x03(\x05\x32T\n\rRatingService\x12\x43\n\x0cUpdateRating\x12\x17.oddsengine.EventResult\x1a\x1a.oddsengine.RatingResponse2]\n\x11PredictionService\x12H\n\x0cPredictEvent\x12\x1a.oddsengine.PredictRequest\x1a\x1c.oddsengine.PredictionRecord2f\n\x11SimulationService\x12Q\n\x0eSimulateSeason\x12\x19.oddsengine.SeasonRequest\x1a\".oddsengine.SeasonSimulationResult0\x01\x42\x18\n\x14\x63om.oddsengine.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.oddsengine.protoP\001'
  _globals['_EVENTRESULT']._serialized_start=44
  _globals['_EVENTRESULT']._serialized_end=138
  _globals['_RATINGRESPONSE']._serialized_start=140
  _globals['_RATINGRESPONSE']._serialized_end=203
  _globals['_PREDICTREQUEST']._serialized_start=205
  _globals['_PREDICTREQUEST']._serialized_end=316
  _globals['_SEASONREQUEST']._serialized_start=318
  _globals['_SEASONREQUEST']._serialized_end=375
  _globals['_SEASONSIMULATIONRESULT']._serialized_start=377
  _globals['_SEASONSIMULATIONRESULT']._serialized_end=446
  _globals['_RATINGSERVICE']._serialized_start=448
  _globals['_RATINGSERVICE']._serialized_end=532
  _globals['_PREDICTIONSERVICE']._serialized_start=534
  _globals['_PREDICTIONSERVICE']._serialized_end=627
  _globals['_SIMULATIONSERVICE']._serialized_start=629
  _globals['_SIMULATIONSERVICE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
