# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import domain_pb2 as domain__pb2
import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RatingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateRating = channel.unary_unary(
                '/oddsengine.RatingService/UpdateRating',
                request_serializer=services__pb2.EventResult.SerializeToString,
                response_deserializer=services__pb2.RatingResponse.FromString,
                _registered_method=True)


class RatingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def UpdateRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RatingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateRating': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRating,
                    request_deserializer=services__pb2.EventResult.FromString,
                    response_serializer=services__pb2.RatingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oddsengine.RatingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oddsengine.RatingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RatingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oddsengine.RatingService/UpdateRating',
            services__pb2.EventResult.SerializeToString,
            services__pb2.RatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PredictionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictEvent = channel.unary_unary(
                '/oddsengine.PredictionService/PredictEvent',
                request_serializer=services__pb2.PredictRequest.SerializeToString,
                response_deserializer=domain__pb2.PredictionRecord.FromString,
                _registered_method=True)


class PredictionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PredictEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictEvent,
                    request_deserializer=services__pb2.PredictRequest.FromString,
                    response_serializer=domain__pb2.PredictionRecord.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oddsengine.PredictionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oddsengine.PredictionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PredictionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oddsengine.PredictionService/PredictEvent',
            services__pb2.PredictRequest.SerializeToString,
            domain__pb2.PredictionRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SimulationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimulateSeason = channel.unary_stream(
                '/oddsengine.SimulationService/SimulateSeason',
                request_serializer=services__pb2.SeasonRequest.SerializeToString,
                response_deserializer=services__pb2.SeasonSimulationResult.FromString,
                _registered_method=True)


class SimulationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SimulateSeason(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimulateSeason': grpc.unary_stream_rpc_method_handler(
                    servicer.SimulateSeason,
                    request_deserializer=services__pb2.SeasonRequest.FromString,
                    response_serializer=services__pb2.SeasonSimulationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oddsengine.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oddsengine.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimulateSeason(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/oddsengine.SimulationService/SimulateSeason',
            services__pb2.SeasonRequest.SerializeToString,
            services__pb2.SeasonSimulationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
